// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCountry = "countries"

// Country mapped from table <countries>
type Country struct {
	CountryID   int32  `gorm:"column:country_id;primaryKey;autoIncrement:true" json:"country_id"`
	CountryName string `gorm:"column:country_name" json:"country_name"`
	RegionID    int32  `gorm:"column:region_id" json:"region_id"`
}

// TableName Country's table name
func (*Country) TableName() string {
	return TableNameCountry
}
