// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDepartment = "departments"

// Department mapped from table <departments>
type Department struct {
	DepartmentID   int32  `gorm:"column:department_id;primaryKey;autoIncrement:true" json:"department_id"`
	DepartmentName string `gorm:"column:department_name;not null" json:"department_name"`
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
