// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployee = "employees"

// Employee mapped from table <employees>
type Employee struct {
	EmployeeID    int32     `gorm:"column:employee_id;primaryKey;autoIncrement:true" json:"employee_id"`
	LastName      string    `gorm:"column:last_name" json:"last_name"`
	Email         string    `gorm:"column:email" json:"email"`
	PhoneNumber   string    `gorm:"column:phone_number" json:"phone_number"`
	HireDate      time.Time `gorm:"column:hire_date" json:"hire_date"`
	CountryID     int32     `gorm:"column:country_id" json:"country_id"`
	Salary        int32     `gorm:"column:salary" json:"salary"`
	DepartmentID  int32     `gorm:"column:department_id" json:"department_id"`
	FirstName     string    `gorm:"column:first_name" json:"first_name"`
	CommissionPct float64   `gorm:"column:commission_pct" json:"commission_pct"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
